<select name="country" id="select-country">
  <option value="">-- Select a country --</option>
  <option value="al">Albania</option>
  <option value="ad">Andorra</option>
  <option value="at">Austria</option>
  <option value="by">Belarus</option>
  <option value="be">Belgium</option>
  <option value="ba">Bosnia and Herzegovina</option>
  <option value="bg">Bulgaria</option>
  <option value="hr">Croatia</option>
  <option value="cy">Cyprus</option>
  <option value="cz">Czech Republic</option>
  <option value="dk">Denmark</option>
  <option value="ee">Estonia</option>
  <option value="fi">Finland</option>
  <option value="fr">France</option>
  <option value="de">Germany</option>
  <option value="gr">Greece</option>
  <option value="hu">Hungary</option>
  <option value="is">Iceland</option>
  <option value="ie">Ireland</option>
  <option value="it">Italy</option>
  <option value="lv">Latvia</option>
  <option value="li">Liechtenstein</option>
  <option value="lt">Lithuania</option>
  <option value="lu">Luxembourg</option>
  <option value="mt">Malta</option>
  <option value="md">Moldova</option>
  <option value="mc">Monaco</option>
  <option value="me">Montenegro</option>
  <option value="nl">Netherlands</option>
  <option value="mk">North Macedonia</option>
  <option value="no">Norway</option>
  <option value="pl">Poland</option>
  <option value="pt">Portugal</option>
  <option value="ro">Romania</option>
  <option value="ru">Russia</option>
  <option value="sm">San Marino</option>
  <option value="rs">Serbia</option>
  <option value="sk">Slovakia</option>
  <option value="si">Slovenia</option>
  <option value="es">Spain</option>
  <option value="se">Sweden</option>
  <option value="ch">Switzerland</option>
  <option value="tr">Turkey</option>
  <option value="ua">Ukraine</option>
  <option value="gb">United Kingdom</option>
  <option value="va">Vatican City</option>
</select>
